Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2023-10, with the labels that each got.

#447 1.7 questbook
  overrides/config/betterquesting/saved_quests/ExpertQuestsDev.json
  overrides/config/betterquesting/saved_quests/NormalQuestsDev.json
  overrides/scripts/_oreDict.zs
Labels: quest-book, high-priority

#460 Fix error parsing complex bodies made on GH
  tools/tasks/changelog/specialParser.ts
Labels: bug

#462 Cleanup + Fix Issues from PR #450
  manifest.json
  overrides/bansoukou/gregtech-2.6.2-beta/assets/gregtech/lang/en_us.lang
  overrides/bansoukou/gregtech-2.6.2-beta/gregtech/common/covers/CoverRoboticArm.class
  tools/templates/randompatches.cfg
Labels: bug

#464 Fix Non Release Commit Workflow
  .github/workflows/releasecommit.yml
Labels: bug

#466 Changelog Improvements
  tools/tasks/changelog/generateModChanges.ts
  tools/tasks/changelog/pusher.ts
Labels: enhancement

#481 Implement Ignore Tag
  tools/tasks/changelog/changelogData.ts
  tools/tasks/changelog/createChangelog.ts
  tools/tasks/changelog/definitions.ts
  tools/tasks/changelog/parser.ts
  tools/tasks/changelog/pusher.ts
  tools/tasks/changelog/specialParser.ts
  tools/types/changelogTypes.ts
  tools/util/util.ts
Labels: enhancement

#478 Allow Changing of Sound Output Device
  manifest.json
Labels: enhancement

#484 Fix Draconic Evolution Crash
  overrides/bansoukou/Draconic-Evolution-1.12.2-2.3.28.354-universal/com/brandon3055/draconicevolution/inventory/ContainerReactor$SlotReactor.class
  overrides/bansoukou/Draconic-Evolution-1.12.2-2.3.28.354-universal/com/brandon3055/draconicevolution/inventory/ContainerReactor.class
  overrides/bansoukou/Draconic-Evolution-1.12.2-2.3.28.354-universal/com/brandon3055/draconicevolution/world/EnergyCoreStructure.class
Labels: bug
