Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-03, with the labels that each got.

#634 Update PackagedAuto From v1.0.8.31 to v1.0.11.40
  manifest.json
Labels: bug

#646 Update BQu from v4.1.0 to v4.2.1
  manifest.json
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/tasks/shared/quest.ts
Labels: enhancement

#653 1.7 Balance Changes
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/lategame.groovy
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/multiblocks_expert.zs
  overrides/scripts/multiblocks_normal.zs
Labels: balancing, blocking

#662 Slightly Increase EB Reach
  overrides/config/EffortlessBuilding.cfg
Labels: enhancement

#669 Remove Harvest Tweak & Night Vision Flash
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: enhancement

#685 Add Distilled Water Variant of Dust -> Clay
  overrides/scripts/normalmode.zs
Labels: bug

#683 Fix Computer Casing Recipe
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/lategame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Mid-Game/midgame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Post-Heart/postHeart.groovy
  tools/.mode
Labels: bug

#682 Disable Vanilla Ores & Slightly Reduce HM Ore Gen
  overrides/config-overrides/expert/gregtech/gregtech.cfg
  overrides/config-overrides/normal/gregtech/gregtech.cfg
  overrides/config/gregtech/gregtech.cfg
Labels: bug

#689 Allow Fixes to Not Replace the Target Commit's Fixes
  tools/tasks/changelog/definitions.ts
  tools/tasks/changelog/parser.ts
  tools/tasks/changelog/specialParser.ts
  tools/types/changelogTypes.ts
Labels: enhancement

#691 Remove Accidentally Added Logs in #689
  tools/tasks/changelog/parser.ts
  tools/tasks/changelog/specialParser.ts
Labels: bug

#687 Update Nomi-Labs from v0.6.20 to v0.6.21
  manifest.json
  overrides/config/EffortlessBuilding.cfg
  overrides/config/nomilabs.cfg
Labels: enhancement

#696 Fix Small Dust, Tiny Dust & Dye Conversion Recipes
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/dyes.groovy
  overrides/scripts/undyeing.zs
Labels: bug, enhancement

#697 Make Silicon Inscriber Recipe Accept OreDict
  overrides/scripts/AE2.zs
Labels: bug

#706 Fix Migration Issues
  manifest.json
  overrides/config/nomilabs.cfg
Labels: bug, blocking

#700 Discord Rich Presence
  manifest.json
  overrides/config/craftpresence.json
Labels: enhancement
