Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-08, with the labels that each got.

#842 Make Naquadah Reactor 2 Recipe ZPM -> UV
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/assemblyLine.groovy
Labels: balancing

#843 Black Steel ABS Recipe
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/materialChanges.groovy
Labels: enhancement, qol

#846 Misc Config Changes
  overrides/config/Universal Tweaks - Tweaks.cfg
  overrides/config/nomilabs.cfg
Labels: bug, enhancement

#847 Fix Glowstone Decomposition Recipe
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/materialChanges.groovy
Labels: bug

#848 Fix Missing DME Sim Chamber Recipes
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/blastFurnace.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mode-Specific/Normal-Mode/dmeSimChamber.groovy
  overrides/scripts/multiblock_dml.zs
Labels: bug

#684 Misc JEI Cleanup
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
  overrides/scripts/Endgame.zs
  overrides/scripts/expertmode.zs
  overrides/scripts/normalmode.zs
Labels: enhancement, jei

#852 Fix GrS Warnings, Black Steel ABS Circuit to 3/13
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/materialChanges.groovy
  overrides/scripts/BlastFurnace.zs
Labels: bug

#854 Fix Edge Case Issues with PAs and Cleanrooms
  manifest.json
Labels: bug

#855 Add Linear XP Scaling
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/Universal Tweaks - Tweaks.cfg
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/config/nomilabs.cfg
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/fluids.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mode-Specific/Normal-Mode/dmeSimChamber.groovy
  overrides/resources/modpack/lang/en_us.lang
  tools/storage/savedQBPorter.json
Labels: enhancement

#857 Add Fillable Tooltip to Various Items
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#858 Hide Modded Buckets from JEI
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
Labels: enhancement, jei

#859 Nether Star Block -> Nether Star Crafting Recipe
  overrides/groovy/postInit/Post-Initial/Main/General/Mid-Game/midgame.groovy
Labels: bug

#860 Allow Tin in AE2 Processor GT Recipes
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
Labels: bug

#861 Fix Nightly Builds
  tools/package-lock.json
  tools/package.json
  tools/tasks/client/index.ts
  tools/tasks/mmc/index.ts
  tools/tasks/server/index.ts
Labels: bug

#863 Use Labs' Server MOTD Substitutions
  manifest.json
  overrides/config/nomilabs.cfg
  serverfiles/server.properties
  tools/gulpfile.ts
  tools/tasks/misc/transformFiles.ts
  tools/tasks/server/index.ts
  tools/tasks/shared/index.ts
  tools/templates/server.properties
  tools/utils/buildConfig.default.json
Labels: bug

#867 Fix #866
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/earlygame.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
Labels: bug

#868 Fix Issues with Sleeping in Void Dimension
  manifest.json
  overrides/config/nomilabs.cfg
Labels: bug

#869 Fix Server GrS Errors
  overrides/config/nomilabs.cfg
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/diodes.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
Labels: bug

#870 Update Nomi-Labs to v0.8.6
  manifest.json
  overrides/config/nomilabs.cfg
Labels: bug

#871 Abolish Draconic Injector Energy Limits
  manifest.json
  overrides/config/nomilabs.cfg
  overrides/config/packageddraconic.cfg
Labels: enhancement, qol

#875 Revamp Badges
  README.md
Labels: enhancement

#879 Make Salt Water Deposit Infinite
  overrides/config/gregtech/worldgen/fluid/overworld/salt_water_deposit.json
Labels: balancing

#880 Improve Packaged Draconic and Drac Fusion Quests
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: quest-book

#881 Fix Recycling Recipes of Tantalum Capacitors
  manifest.json
Labels: bug

#883 Small Quest Book Cleanup
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: quest-book

#884 Improve Port QB Task
  tools/globals.ts
  tools/gulpfile.ts
  tools/storage/savedQBPorter.json
  tools/tasks/helpers/questPorting/index.ts
  tools/tasks/helpers/questPorting/portQBData.ts
  tools/tasks/helpers/questPorting/portQBModifications.ts
  tools/utils/util.ts
Labels: enhancement

#885 Fix Dupe Glitch with BogoSorter and Thermal Satchels
  manifest.json
Labels: bug

#886 Fix Porting QB Changes from Expert to Normal
  tools/tasks/helpers/questPorting/portQBData.ts
Labels: bug

#887 Fix Inventory BogoSorter Default Sort Keybind
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
  tools/storage/savedQBPorter.json
Labels: bug

#888 Change Default Sort Keybind back to Middle Click
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
Labels: enhancement

#889 Fix Auto Remote Fetching from Nomi-CEu/Nomi-CEu
  tools/tasks/helpers/questPorting/portQBData.ts
Labels: bug

#890 More Fixes for Auto Fetch Nomi-CEu/Nomi-CEu
  tools/tasks/helpers/questPorting/portQBData.ts
Labels: bug

#891 Fix Voiding and Recipe Search Issues with Large Distllery
  manifest.json
Labels: bug

#892 Update Nomi Labs to v0.8.10
  manifest.json
Labels: bug

#893 New FTB Utilities Default Settings
  overrides/local/ftbutilities/ranks.txt
Labels: enhancement

#895 Significantly Reduce Github API Requests
  tools/tasks/changelog/pusher.ts
  tools/utils/util.ts
Labels: bug

#904 Small Buildscript Improvements
  tools/buildConfig.ts
  tools/package-lock.json
  tools/package.json
  tools/tasks/changelog/pusher.ts
  tools/tasks/deploy/releases.ts
  tools/utils/util.ts
Labels: bug

#907 Apply Prettier to Manifest
  manifest.json
Labels: enhancement

#908 Update Labs to v0.8.11
  manifest.json
  overrides/config/nomilabs.cfg
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
Labels: bug

#909 Unhide Parabolic Flux Coupling
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/thermal.groovy
Labels: bug

#914 Make Tier IV Jetpack Hover Mode Stable
  overrides/config/simplyjetpacks-client.cfg
  overrides/config/simplyjetpacks.cfg
Labels: enhancement

#915 Fix Incorrect Outputs for Some ABS Recipes
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/blastFurnace.groovy
Labels: bug

#916 Fix Sleeping in Void Dimension not Resetting Weather
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
Labels: bug

#920 Fix Occasional Errors with GrS
  manifest.json
Labels: bug

#921 Fix README CurseForge Links
  README.md
Labels: bug

#923 Add Fluid Attributes to Labs Fluids
  manifest.json
Labels: enhancement

#926 Fix Edge Case Voiding Outputs in Parallel Recipes
  manifest.json
Labels: bug

#930 Add Tooltips for the Hyper Acceleration Card
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#931 Add Tooltips for the Inverter Card
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#933 Small QB Porter Fixes
  tools/tasks/helpers/questPorting/portQBData.ts
  tools/tasks/helpers/questPorting/portQBModifications.ts
Labels: bug

#928 Update Quest Book for AE2 & NAE2 Updates
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/scripts/_oreDict.zs
  tools/storage/savedQBPorter.json
Labels: quest-book

#937 Add Tooltip Warnings for Various AE2 Items
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
  overrides/resources/nae2/lang/en_us.lang
Labels: enhancement

#939 Fix BQu Detection of Fluids with Stacked Fluid Containers
  manifest.json
Labels: bug

#943 Fix Draconic Energy Storage Core Crash
  overrides/config/Universal Tweaks - Mod Integration.cfg
Labels: bug

#948 Format 'Infinite' Potion Effects as **/**
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: enhancement

#949 Actually Make XP Bottles Drop 25 XP
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: bug

#950 Misc AE2 Fixes and Improvements
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/AppliedEnergistics2/AppliedEnergistics2.cfg
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/blocks.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: bug, enhancement

#951 Update Nomi-Labs to v0.8.18
  manifest.json
  overrides/config/betterquesting/DefaultQuests.json
Labels: bug, enhancement

#952 Fix QB Formatting
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
Labels: bug

#940 Misc QB Fixes
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
Labels: quest-book

#946 Add Nomicoin-Free Airtight Seal Recipes
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/advancedRocketry.groovy
Labels: enhancement

#953 Fix Edge Case Advanced Rocketry Crash
  overrides/config/advRocketry/planetDefs.xml
Labels: bug

#957 Allow Flying To/From Lost Cities + Unlock All Planets
  overrides/config/advRocketry/planetDefs.xml
Labels: enhancement

#958 Fix Inefficient ABS Recipe Durations
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/blastFurnace.groovy
Labels: bug

#959 Add a FPS Impact Warning to EIO Facades
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#960 Hide BQu Loot Boxes from JEI
  overrides/config/betterquesting.cfg
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
Labels: enhancement

#961 Hide Better Questing Placeholders from JEI
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
Labels: enhancement

#962 QB Formatting Improvements Relating to Spaces
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/tasks/helpers/questChecks/index.ts
Labels: bug, enhancement

#963 Add Recycling Recipes for Inscriber Presses
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy
Labels: enhancement

#964 Slightly Improve HM's Assembly Line Automation Quest
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
Labels: quest-book

#966 Fix Transformation of Issue/PR Tags in Changelog
  tools/tasks/changelog/pusher.ts
Labels: bug

#967 Update Nomi-Labs to v0.8.19
  manifest.json
Labels: bug

#970 Replace Forgelin and Librarian Lib with Forked Versions
  manifest.json
Labels: bug

#971 Fix Auto Completing HPCA Quest
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: bug, quest-book

#973 Update Nomi Labs and Vintage Fix
  manifest.json
Labels: bug

#975 Update Labs Config
  overrides/config/nomilabs.cfg
Labels: bug
