Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-10, with the labels that each got.

#1014 Fix NBT Problems in Pure Crystal Shortcut Recipes
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
Labels: bug

#1016 Update Alfheim Lighting Engine to 1.4
  manifest.json
Labels: enhancement

#1015 Update CraftPresence to v2.5.0
  manifest.json
  overrides/config/craftpresence.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
Labels: enhancement

#1018 Make Fork PR Build Only Run on Certain PRs
  .github/workflows/forkprbuildpack.yml
Labels: enhancement

#1020 Allow Skipping Changelog Generation, Fix Lang Zips
  .github/workflows/buildpack.yml
  .github/workflows/forkprbuildpack.yml
  .github/workflows/testbuildpack.yml
  overrides/resources/pack.mcmeta
  tools/tasks/client/index.ts
  tools/tasks/lang/index.ts
  tools/tasks/mmc/index.ts
  tools/tasks/server/index.ts
  tools/tasks/shared/index.ts
  tools/utils/util.ts
Labels: bug, enhancement

#1021 Use Faster Hashing Library
  tools/gulpfile.ts
  tools/package-lock.json
  tools/package.json
  tools/tasks/misc/downloadMods.ts
  tools/tasks/misc/pruneCache.ts
  tools/tasks/mmc/index.ts
  tools/utils/buildConfig.default.json
  tools/utils/hashes.ts
  tools/utils/util.ts
Labels: enhancement

#1022 Properly Signal Async Completion with Streams
  tools/tasks/client/index.ts
  tools/tasks/lang/index.ts
  tools/tasks/misc/zip.ts
  tools/tasks/mmc/index.ts
  tools/tasks/server/index.ts
  tools/tasks/shared/index.ts
  tools/utils/util.ts
Labels: bug

#1023 Make Changelog Once for Seperate Builds
  .github/workflows/buildpack.yml
  .github/workflows/checks.yml
  .github/workflows/testbuildpack.yml
  .github/workflows/testcommits.yml
  tools/gulpfile.ts
  tools/tasks/shared/index.ts
Labels: enhancement

#1024 Fix Hand Framing Display Recipes
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
Labels: bug

#1025 Fix ME Conduit Recipe
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/eio.groovy
  overrides/scripts/electronics.zs
Labels: bug

#1026 Alternative ULV Covers Recipes
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/earlygame.groovy
Labels: enhancement, balancing

#1029 Fix Transmutating Airtight Seal Recipe
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/advancedRocketry.groovy
Labels: bug

#1030 Alternative Lubricant Recipes
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/earlygame.groovy
Labels: balancing

#1027 Alternative Hull Recipes with Higher Tier Plastics
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/hulls.groovy
Labels: enhancement, balancing

#1007 Misc Questbook Fixes and Improvements
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: enhancement, quest-book

#1032 Slight Cleanup with Newer APIs
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/hulls.groovy
Labels: enhancement

#1033 Update to Nomi Labs 0.9.1
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/nbtClearing.groovy
Labels: bug, enhancement

#1034 Fix Hand Framing Display Recipes
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
Labels: bug

#1036 Fix Potassium Duplication in PGS EBF Step
  overrides/scripts/expert_processing.zs
Labels: HM, balancing

#1037 Allow Specifying Co-Authors in Changelog
  tools/tasks/changelog/changelogData.ts
  tools/tasks/changelog/definitions.ts
  tools/tasks/changelog/parser.ts
  tools/tasks/changelog/pusher.ts
  tools/tasks/changelog/specialParser.ts
  tools/types/changelogTypes.ts
Labels: enhancement

#1035 Content Clearing Recipes
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/nbtClearing.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#1039 Fix GregTech Facades' Tooltip
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: bug

#1038 Cleanup of Quest Book Layout
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: quest-book

#1041 Advanced Rocketry Tank Improvements
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
Labels: bug, enhancement

#1042 Fix Airtight Seal Recipes
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/advancedRocketry.groovy
Labels: bug, balancing, blocking

#1043 Misc Quest Fixes and Cleanup
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: quest-book

#1046 Fix Typo in Fusion Reactor MK I Quest
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: quest-book

#1047 Update Wiki Links
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/ISSUE_TEMPLATE/002-feature-request.yml
  overrides/config/CustomMainMenu/mainmenu.json
  overrides/config/nomilabs-version.cfg
  tools/tasks/changelog/specialParser.ts
  tools/tasks/misc/transformFiles.ts
  tools/tasks/shared/quest.ts
Labels: bug

#1048 Fix Server Side GrS Error
  overrides/config/nomilabs.cfg
Labels: bug

#1051 Fix Issues with Loading Labs Config on Cleanroom Servers
  manifest.json
Labels: bug

#1054 Use Wiki in Server Info File, Mention in README
  README.md
  serverfiles/README.md
Labels: enhancement

#1055 Fix Vibrant Jetpack Recipe
  overrides/scripts/JetpacksAndEnergyStorage.zs
  overrides/scripts/common.zs
Labels: bug

#1058 Improve Circuit Etcher Recipe (Lazy AE2 Compat)
  overrides/scripts/AddonScripts/LazyAE2.zs
Labels: enhancement

#1061 Fix Empty Locked Drawers Resetting on World Load
  manifest.json
Labels: bug

#1064 Update Nomi-Labs to 0.10.0
  manifest.json
  overrides/config/nomilabs.cfg
Labels: bug, enhancement

#1066 Add Tooltips Saying P2P Type
  overrides/groovy/classes/postInit/common.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/p2p.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: enhancement

#1068 Emphasise Steam Vent Mechanics
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
Labels: quest-book

#1067 Add the FindMyItemsAndFluids Mod
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
Labels: enhancement

#1065 Hide Higher Tier Muffler Hatches
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/config/nomilabs.cfg
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/jei.groovy
  overrides/resources/gregtech/lang/en_us.lang
  tools/storage/savedQBPorter.json
Labels: enhancement

#1072 Fix Wrong Default Visibility in Quest Transform Task
  tools/tasks/shared/quest.ts
Labels: bug

#1073 More Fixes for Randomly Unlocking Drawers
  manifest.json
Labels: bug

#1078 Make Double Check on Terminal Default False
  overrides/config/gregtech/terminal/config/os_settings.nbt
Labels: enhancement

#1079 Add Tiny Coke
  manifest.json
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/earlygame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
Labels: enhancement

#1080 Fix Server Crash
  overrides/config/nomilabs.cfg
Labels: bug

#1082 Fix Changelog Downloading from Branch
  tools/tasks/shared/index.ts
Labels: bug

#1083 Remove Versions Before 1.6 From Issue Templates
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/ISSUE_TEMPLATE/002-feature-request.yml
  tools/templates/versions.txt
Labels: documentation-or-lang

#1084 Remove Prune Cache Task from Build Tasks
  tools/gulpfile.ts
Labels: enhancement

#1094 Update LoliASM Config
  overrides/config/loliasm.cfg
Labels: enhancement
