Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-07, with the labels that each got.

#776 Add Packaged Draconic
  manifest.json
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/draconicFusion.groovy
Labels: enhancement, qol

#789 Rebalance Expert Mode Endervoir Recipe to Output 4
  overrides/scripts/expertmode.zs
Labels: balancing

#790 Update Nomi-Labs, GT, GCYM, GrS and More
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/ISSUE_TEMPLATE/002-feature-request.yml
  README.md
  manifest.json
  overrides/README.md
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/expert/difficultylock.cfg
  overrides/config-overrides/expert/randompatches.cfg
  overrides/config-overrides/expert/server.properties
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/difficultylock.cfg
  overrides/config-overrides/normal/randompatches.cfg
  overrides/config-overrides/normal/server.properties
  overrides/config/CustomMainMenu/mainmenu.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/config/defaultworldgenerator-port/worldsettings.data
  overrides/config/difficultylock.cfg
  overrides/config/justenoughdimensions/dimensions.json
  overrides/config/justenoughdimensions/justenoughdimensions.cfg
  overrides/config/nomilabs-version.cfg
  overrides/config/nomilabs.cfg
  overrides/config/randompatches.cfg
  overrides/groovy/postInit/Post-Initial/Main/General/Mid-Game/midgame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/blocks.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy
  overrides/resources/minecraft/lang/en_us.lang
  overrides/resources/modpack/textures/logo/16x.png
  overrides/resources/modpack/textures/logo/32x.png
  overrides/scripts/AdvRocketry.zs
  pack-mode-switcher.bat
  pack-mode-switcher.sh
  serverfiles/server.properties
  tools/gulpfile.ts
  tools/storage/savedQBPorter.json
  tools/tasks/client/index.ts
  tools/tasks/misc/transformFiles.ts
  tools/tasks/misc/zip.ts
  tools/tasks/mmc/index.ts
  tools/tasks/server/index.ts
  tools/tasks/shared/index.ts
  tools/templates/nomilabs-version.cfg
  tools/templates/randompatches.cfg
  tools/templates/server.properties
  tools/templates/server_expert.properties
  tools/templates/versions.txt
Labels: bug, enhancement, high-priority

#794 Update Universal Tweaks to v1.11.0
  manifest.json
  overrides/config/Universal Tweaks - Bugfixes.cfg
  overrides/config/Universal Tweaks - Mod Integration.cfg
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: enhancement

#795 Update Misc Config
  overrides/config/AE2Stuff/overrides/recipes.cfg
  overrides/config/AE2Stuff/overrides/tuning.cfg
  overrides/config/AE2Stuff/readme.txt
  overrides/config/AppliedEnergistics2/VersionChecker.cfg
  overrides/config/forgivingvoid.cfg
Labels: bug, enhancement

#796 Port Tooltips to Groovy + Fix Fluids in JEI
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/fluids.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
  overrides/scripts/AE2.zs
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/Alchemy.zs
  overrides/scripts/AppliedEnergistics2.zs
  overrides/scripts/Darkutils.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/JEICleanup.zs
  overrides/scripts/Microverse.zs
  overrides/scripts/ProjectRed.zs
  overrides/scripts/_oreDict.zs
  overrides/scripts/aa xu2.zs
  overrides/scripts/dml.zs
  overrides/scripts/normalmode.zs
  overrides/scripts/xTones.zs
Labels: bug, enhancement

#799 Cleanup Thermal and EIO Items in JEI
  overrides/groovy/classes/postInit/eioPrefixes.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/eio.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/thermal.groovy
  overrides/resources/modpack/lang/en_us.lang
  overrides/scripts/_oreDict.zs
  overrides/scripts/extendedcrafting.zs
Labels: bug, jei

#798 Tooltip Fixes and Enhancements
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
Labels: bug, enhancement

#800 Fix Server Crashes
  manifest.json
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
Labels: bug

#802 Fix Corrupted Server Icon
  tools/tasks/server/index.ts
Labels: bug

#801 Fix AE2 Inscriber Recipes
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy
Labels: bug

#807 Enable Difficulty Lock
  overrides/config/nomilabs.cfg
Labels: bug

#808 Replace AE2 Stuff with AE2 Stuff Unofficial
  manifest.json
Labels: bug, enhancement

#812 Fix Fluid Storage Component Recipes in HM
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/blocks.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/nae2.groovy
  overrides/scripts/expertmode.zs
Labels: bug, HM

#813 Update Nomi Labs to 0.7.9
  manifest.json
Labels: bug, enhancement

#811 Fix Advanced Disclocator Recipe
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/draconicFusion.groovy
Labels: bug

#815 Fix Edge Case Corruption on Worlds Loaded in 1.7-beta-5
  manifest.json
  tools/templates/nomilabs-version.cfg
Labels: bug

#816 Update Template Commit Messages
  .github/workflows/releasecommit.yml
Labels: bug

#817 Make Transform QB Workflow use IDs
  tools/tasks/shared/quest.ts
Labels: enhancement

#818 Cleanup Dyes Groovy Script
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/dyes.groovy
Labels: enhancement

#819 Update PackagedExCrafting and PackagedAuto
  manifest.json
Labels: bug

#820 Update Universal Tweaks to v1.12.0
  manifest.json
  overrides/config/Universal Tweaks - Bugfixes.cfg
  overrides/config/Universal Tweaks - Mod Integration.cfg
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: bug, enhancement

#826 Fix Draconic Energy Core Integration
  overrides/config/groovyscript.cfg
Labels: bug

#828 Fix GrS Errors Introduced in #822
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/thermal.groovy
Labels: bug

#829 Revamp of Commit Authors in Changelog
  tools/tasks/changelog/generateModChanges.ts
  tools/tasks/changelog/pusher.ts
  tools/types/changelogTypes.ts
  tools/utils/util.ts
Labels: enhancement

#835 Fix Thermal Cycle Item Mode Keybind
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/keybindOverrides.groovy
Labels: bug

#831 Add Debug Log Output to Dedicated Servers
  serverfiles/log4j2_112-116.xml
Labels: enhancement

#840 Cleanup NuclearCraft JEI Removals
  overrides/scripts/Nuclearcraft.zs
Labels: bug

#837 Fix Duplicate Prospector Tooltip + Cleanup
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/resources/extendedcrafting/lang/en_us.lang
  overrides/resources/modpack/lang/en_us.lang
  overrides/resources/nomiceu/lang/en_us.lang
  overrides/scripts/Earlygame.zs
Labels: bug, enhancement

#836 Fix NC Fluids in JEI
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/fluids.groovy
Labels: bug

#832 Primal Mana -> Mana Dust Solidifier Recipe
  overrides/scripts/extractor_solidifier.zs
Labels: enhancement, qol

#833 Add Alternate and Balance Implosion Recipes for Omnium
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/lategame.groovy
  overrides/scripts/Earlygame.zs
  overrides/scripts/extendedcrafting.zs
Labels: enhancement, qol

#838 Update Nomi-Labs to v0.8.0
  manifest.json
  overrides/groovy/classes/postInit/common.groovy
  overrides/groovy/classes/postInit/eioPrefixes.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/earlygame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Early-Game/electronics.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/assemblyLine.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Late-Game/lategame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Mid-Game/midgame.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/blastFurnace.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/diodes.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/handFraming.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/materialChanges.groovy
  overrides/groovy/postInit/Post-Initial/Main/General/Misc/tooltips.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/p2p.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/eio.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/nuclearcraft.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mode-Specific/Expert-Mode/stabilizedMiners.groovy
  overrides/groovy/postInit/Post-Initial/Main/Mode-Specific/Normal-Mode/buses.groovy
  overrides/groovy/runConfig.json
  overrides/resources/modpack/lang/en_us.lang
  overrides/scripts/Endgame.zs
  overrides/scripts/expertmode.zs
Labels: bug, enhancement, qol
