Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-06, with the labels that each got.

#759 Fix #756, Port Silicone/Styrene Choice to HM
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
  tools/tasks/helpers/questChecks/index.ts
Labels: bug

#772 Add Lategame GT Recipes for AE2 Components
  overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/items.groovy
Labels: enhancement, balancing, qol

#782 Change Void Oil Deposit Back to Raw Oil
  overrides/config/gregtech/worldgen/fluid/void/infinite_raw_oil_deposit.json
Labels: balancing
