Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2024-09, with the labels that each got.

#976 Stop Registration of Advanced Rocketry's Recipes
  overrides/config/advRocketry/ChemicalReactor.xml
  overrides/config/advRocketry/Crystallizer.xml
  overrides/config/advRocketry/CuttingMachine.xml
  overrides/config/advRocketry/ElectricArcFurnace.xml
  overrides/config/advRocketry/Electrolyser.xml
  overrides/config/advRocketry/Lathe.xml
  overrides/config/advRocketry/PrecisionAssembler.xml
  overrides/config/advRocketry/RollingMachine.xml
  overrides/config/advRocketry/SmallPlatePress.xml
Labels: enhancement

#977 Add Pack Mode Switcher to GitHub and Nightly Builds
  .github/workflows/buildpack.yml
  tools/gulpfile.ts
  tools/tasks/changelog/index.ts
  tools/tasks/deploy/curseforge.ts
  tools/tasks/misc/zip.ts
  tools/tasks/shared/index.ts
  tools/utils/buildConfig.default.json
  tools/utils/util.ts
Labels: enhancement

#978 Update README with Included Pack Mode Scripts
  README.md
  overrides/README.md
Labels: documentation-or-lang

#979 Update Link and Alternate Text for Star Badge
  README.md
Labels: documentation-or-lang

#980 Fix CurseForge Upload Task Not Using CF Zips
  tools/tasks/deploy/curseforge.ts
Labels: bug

#981 Remove Checkout of Tag in CF and GitHub Deployment
  .github/workflows/deploycf.yml
  .github/workflows/deploygh.yml
Labels: enhancement

#982 Fix Create Changelog Deprecated Node Usage
  .github/workflows/createchangelog.yml
Labels: bug

#986 Fix Typo in First Micro Miner Quest
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  tools/storage/savedQBPorter.json
Labels: bug, quest-book

#992 Fix Issues with Searching Tooltips in JEI
  overrides/config/Universal Tweaks - Tweaks.cfg
Labels: bug

#994 Fix Buildscript Vulnerabilities
  tools/package-lock.json
Labels: bug

#1002 Add T4.5MM as a Dependency to Soul Binder Quest
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
Labels: quest-book
