Repository Nomi-CEu/Nomi-CEu, pull requests merged in 2025-03, with the labels that each got.

#1236 Fix Changelogs in CI Build Packs
  .github/workflows/testbuildpack.yml
Labels: bug

#1254 Update Nomi Labs to v0.14.3
  manifest.json
Labels: enhancement

#1255 Add Typo Checking CI Tasks
  .github/workflows/buildpack.yml
  .github/workflows/checks.yml
  .github/workflows/createchangelog.yml
  .github/workflows/deploy.yml
  .github/workflows/releasechangelog.yml
  .github/workflows/releasedeploy.yml
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  tools/globals.ts
  tools/gulpfile.ts
  tools/package-lock.json
  tools/package.json
  tools/tasks/helpers/langExtract.ts
  tools/tasks/lang/index.ts
  tools/tasks/shared/index.ts
Labels: enhancement

#1257 Fix Fractionating Distillery Edge Case Crash
  manifest.json
Labels: bug

#1258 Expand Typo CI to Cover READMEs
  .github/workflows/checks.yml
Labels: enhancement

#1261 Rework Yields for the EM Separator
  overrides/groovy/postInit/main/general/midGame/midgame.groovy
Labels: balancing

#1266 Fix Certain Nuclear Isotope Fluids Missing from JEI
  overrides/groovy/postInit/main/modSpecific/nuclearcraft.groovy
Labels: bug

#1268 Hide Thermal Excavators from JEI
  overrides/groovy/postInit/main/modSpecific/thermal.groovy
Labels: enhancement

#1264 Remove Useless NuclearCraft Isotopes Recipes
  overrides/groovy/postInit/main/modSpecific/nuclearcraft.groovy
Labels: jei

#1267 Misc Quest Book Fixes and Improvements: Round 2
  overrides/config-overrides/expert/betterquesting/DefaultQuests.json
  overrides/config-overrides/normal/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/betterquesting/saved_quests/ExpertQuests.json
  overrides/groovy/postInit/main/general/misc/questbookOreDicts.groovy
  overrides/groovy/postInit/main/general/misc/tooltips.groovy
  overrides/resources/modpack/lang/en_us.lang
  tools/storage/savedQBPorter.json
Labels: quest-book

#1272 Remove Erroring Extractor Recipe
  overrides/scripts/Nuclearcraft.zs
Labels: bug

#1273 Add OreDict to Radium Salt
  overrides/groovy/postInit/main/general/midGame/midgame.groovy
Labels: enhancement

#1281 Fix Erroring Manifest
  manifest.json
  tools/utils/curseForgeAPI.ts
Labels: bug
